//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsenseOfficial.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multilingual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multilingual() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XsenseOfficial.ResourceFiles.Multilingual", typeof(Multilingual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 350401 新竹科學園區苗栗縣竹南鎮科北一路21號3樓 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行政問題 的當地語系化字串。
        /// </summary>
        public static string ContactAdminIssue {
            get {
                return ResourceManager.GetString("ContactAdminIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string ContactContent {
            get {
                return ResourceManager.GetString("ContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡表單 的當地語系化字串。
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 感謝您光臨艾格生科技股份有限公司網站，您的寶貴意見讓我們持續成長。誠摯的歡迎您來信或來電洽詢相關業務，我們將盡快提供您完整的服務，謝謝。 的當地語系化字串。
        /// </summary>
        public static string ContactFormContent {
            get {
                return ResourceManager.GetString("ContactFormContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡資訊 的當地語系化字串。
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他問題 的當地語系化字串。
        /// </summary>
        public static string ContactOtherIssue {
            get {
                return ResourceManager.GetString("ContactOtherIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連絡電話 的當地語系化字串。
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品問題 的當地語系化字串。
        /// </summary>
        public static string ContactProductIssue {
            get {
                return ResourceManager.GetString("ContactProductIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主旨 的當地語系化字串。
        /// </summary>
        public static string ContactSubject {
            get {
                return ResourceManager.GetString("ContactSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 技術問題 的當地語系化字串。
        /// </summary>
        public static string ContactTechIssue {
            get {
                return ResourceManager.GetString("ContactTechIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司位置 的當地語系化字串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 了解更多 的當地語系化字串。
        /// </summary>
        public static string 了解更多 {
            get {
                return ResourceManager.GetString("了解更多", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 企業永續經營 的當地語系化字串。
        /// </summary>
        public static string 企業永續經營 {
            get {
                return ResourceManager.GetString("企業永續經營", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 供應商管理 的當地語系化字串。
        /// </summary>
        public static string 供應商管理 {
            get {
                return ResourceManager.GetString("供應商管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司介紹 的當地語系化字串。
        /// </summary>
        public static string 公司介紹 {
            get {
                return ResourceManager.GetString("公司介紹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 艾格生科技 的當地語系化字串。
        /// </summary>
        public static string 公司名稱 {
            get {
                return ResourceManager.GetString("公司名稱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入我們 的當地語系化字串。
        /// </summary>
        public static string 加入我們 {
            get {
                return ResourceManager.GetString("加入我們", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品質政策 的當地語系化字串。
        /// </summary>
        public static string 品質政策 {
            get {
                return ResourceManager.GetString("品質政策", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 艾格生科技 學習發展體系 的當地語系化字串。
        /// </summary>
        public static string 學習發展體系 {
            get {
                return ResourceManager.GetString("學習發展體系", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 核心競爭力 的當地語系化字串。
        /// </summary>
        public static string 核心競爭力 {
            get {
                return ResourceManager.GetString("核心競爭力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 環安重要記事 的當地語系化字串。
        /// </summary>
        public static string 環安重要記事 {
            get {
                return ResourceManager.GetString("環安重要記事", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品中心 的當地語系化字串。
        /// </summary>
        public static string 產品中心 {
            get {
                return ResourceManager.GetString("產品中心", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關證照 的當地語系化字串。
        /// </summary>
        public static string 相關證照 {
            get {
                return ResourceManager.GetString("相關證照", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 礦產衝突聲明 的當地語系化字串。
        /// </summary>
        public static string 礦產衝突聲明 {
            get {
                return ResourceManager.GetString("礦產衝突聲明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 福利介紹 的當地語系化字串。
        /// </summary>
        public static string 福利介紹 {
            get {
                return ResourceManager.GetString("福利介紹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        public static string 聯絡我們 {
            get {
                return ResourceManager.GetString("聯絡我們", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 艾格生的生活 的當地語系化字串。
        /// </summary>
        public static string 艾格生的生活 {
            get {
                return ResourceManager.GetString("艾格生的生活", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 里程碑 的當地語系化字串。
        /// </summary>
        public static string 里程碑 {
            get {
                return ResourceManager.GetString("里程碑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於艾格生 的當地語系化字串。
        /// </summary>
        public static string 關於我們 {
            get {
                return ResourceManager.GetString("關於我們", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 願景 的當地語系化字串。
        /// </summary>
        public static string 願景 {
            get {
                return ResourceManager.GetString("願景", resourceCulture);
            }
        }
    }
}
